version: '2.1'
services:

  django:
    image: fei2024tp:0.2
    build:
      context: ./config/django-image
    volumes:
      - ./src/backend:/usr/src/app:delegated
    environment:
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
    ports:
      - "8000:8000"
    networks:
      red:





  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql:delegated
    networks:
      red:

networks:
  red:



